local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>cf', function() vim.lsp.buf.format() end, {})
vim.keymap.set('n', '<C-f>', builtin.lsp_references, {})
vim.keymap.set("i", "<S-Tab>", "<C-d>", { noremap = true })
-- vim.keymap.set("i", "<C-k>", vim.lsp.buf.signature_help)
vim.keymap.set("i", "<C-s>", "<Nop>")
vim.keymap.set("n", "<F2>", vim.lsp.buf.rename, { desc = "Rename symbol" })
